server:
  port: 7475
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: sample-group
      auto-offset-reset: earliest
  application:
    name: NovaRideBookingService

  datasource:
    url: jdbc:mysql://localhost:3306/nova_local_db
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
  show-sql: true
  hibernate:
    ddl-auto: validate


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  instance:
          preferIpAddress: true




